### ISSUE TITLE
[translatesfx] doesn't combine multiple Monitors from other file

### ISSUE THREAD

**Issue by AchimGrolimund** [signalfx/splunk-otel-collector#1228]
I have a root file from there i want to translate around 300 monitors. But on a test i have an file with 2 http monitors but the translator writes only the latest in the new file.

here is the Structure of my files:
├──agent.yaml
├──monitors
........├──agent.yaml
........├──http_test.yaml

### agent.yaml
```yaml
signalFxAccessToken: enWA
ingestUrl: https://sfxgw/ingest/
apiUrl: https://sfxgw/api/
eventEndpointUrl: https://sfxgw/ingest/v2/event
intervalSeconds: 10
logging:
# Valid values are 'debug', 'info', 'warning', and 'error'
level: info

# observers are what discover running services in the environment
observers:
- type: host
procPath: /proc

monitors:
- {"#from": "/monitors/*.yaml", flatten: true, optional: true}

```

### monitors/agent.yaml
```yaml
- type: host-metadata

- type: telegraf/procstat
  exe: "signalfx-agent*"
  datapointsToExclude:
   - metricNames:
      - procstat*
      - '!procstat.pid'
      - '!procstat.cpu_usage'
      - '!procstat.memory_vms'
```

### monitors/http_test.yaml
```yaml
- type: http
  intervalSeconds: 120
  disableHostDimensions: true
  extraDimensions:
    application: '111'
    environment: PROD
    app_abbreviation: 111
    leanix_id: '111'
    Location: '111'
  host: '111.ch'
  port: 8003
  path: '/111'
  useHTTPS: false
  skipVerify: false
  
- type: http
  intervalSeconds: 120
  disableHostDimensions: true
  extraDimensions:
    application: '222'
    environment: PROD
    app_abbreviation: 222
    leanix_id: '222'
    Location: '222'
  host: '222.ch'
  port: 8003
  path: '/222'
  useHTTPS: false
  skipVerify: false
```

### Result from Translator
```yaml
# Generated by 'translatesfx'. This tool is currently experimental. Please
# verify config before attempting to use in production.
config_sources:
  include: null
extensions:
  host_observer: {}
  smartagent:
    procPath: /proc
receivers:
  smartagent/host-metadata:
    type: host-metadata
  smartagent/http:
    disableHostDimensions: true
    extraDimensions:
      Location: "222"
      app_abbreviation: 222
      application: "222"
      environment: PROD
      leanix_id: "222"
    host: 222.ch
    intervalSeconds: 120
    path: /222
    port: 8003
    skipVerify: false
    type: http
    useHTTPS: false
  smartagent/telegraf/procstat:
    datapointsToExclude:
    - metricNames:
      - procstat*
      - '!procstat.pid'
      - '!procstat.cpu_usage'
      - '!procstat.memory_vms'
    exe: signalfx-agent*
    type: telegraf/procstat
processors:
  resourcedetection:
    detectors:
    - system
    - env
    - gce
    - ecs
    - ec2
    - azure
exporters:
  signalfx:
    access_token: enWA
    api_url: https://sfxgw/api/
    ingest_url: https://sfxgw/ingest/
service:
  pipelines:
    metrics:
      receivers:
      - smartagent/host-metadata
      - smartagent/http
      - smartagent/telegraf/procstat
      processors:
      - resourcedetection
      exporters:
      - signalfx
  extensions:
  - host_observer
  - smartagent
```

you can see the `http` monitor with the Host 111 is missing.

the files ar addet as attachement

Best Regards Achim

[SFX_translate.zip](https://github.com/signalfx/splunk-otel-collector/files/8041151/SFX_translate.zip)
