### ISSUE TITLE
time_parser not parsing timestamps from the year 1970 correctly

### ISSUE THREAD

**Issue by dnitschke-splunk** [signalfx/splunk-otel-collector#1232]
### Description
Using `time_parser` operator in a `filelog` receiver does not parse timestamps from the year 1970 correctly. Looks like timestamps starting Fri 1 Jan 1971 00:00:00 UTC are parsed correctly.

### Setup
- Ubuntu 20.04.2
- otelcol version v0.43.0

### Steps to reproduce
Create a file `/tmp/test_timestamp.log` with following content:
```
0
31535999
31536000
1609459200
1640995199
1640995200
``` 
These numbers represent the seconds since the epoch for the following timestamps:
- Thu 1 Jan 1970 00:00:00 UTC
- Thu 31 Dec 1970 23:59:59 UTC
- Fri 1 Jan 1971 00:00:00 UTC
- Fri 1 Jan 2021 00:00:00 UTC
- Fri 31 Dec 2021 23:59:59 UTC
- Sat 1 Jan 2022 00:00:00 UTC

Monitor the file using a `filelog` receiver and write data to a new file `/tmp/otel.out` as configured in the `agent_config.yaml` below. Check the output file and compare the fields `timeUnixNano` and the corresponding `stringValue` for the `timestamp` key in `attributes`. The two timestamps `0` and `31535999` from 1970 are actually parsed as `16409952000` (Sat 1 Jan 2022 00:00:00 UTC) and `1640995199` (Fri 31 Dec 2021 23:59:59 UTC), respectively. The other example timestamps are parsed correctly.

Same experience when using `layout_type: gotime` or `layout_type: strptime`.

### agent_config.yaml
```
extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  http_forwarder:
    ingress:
      endpoint: 0.0.0.0:6060
    egress:
      endpoint: "${SPLUNK_API_URL}"
  smartagent:
    bundleDir: "${SPLUNK_BUNDLE_DIR}"
    collectd:
      configDir: "${SPLUNK_COLLECTD_DIR}"
  zpages:
  memory_ballast:
    size_mib: ${SPLUNK_BALLAST_SIZE_MIB}

receivers:
  filelog/test_timestamp:
    include: 
      - /tmp/test_timestamp.log
    start_at: beginning
    operators:
      - id: timestamp_parsing
        type: time_parser
        parse_from: $$body
        preserve_to: $$attributes['timestamp']
        layout_type: epoch
        layout: s

processors:
  batch:
  memory_limiter:
    check_interval: 2s
    limit_mib: ${SPLUNK_MEMORY_LIMIT_MIB}
  resourcedetection:

exporters:
  file:
    path: /tmp/otel.out

service:
  telemetry:
    logs:
      level: "debug"
  extensions: [health_check, http_forwarder, zpages, memory_ballast, smartagent]
  pipelines:
    logs:
      receivers:
        - filelog/test_timestamp
      processors:
        - memory_limiter
        - batch
      exporters:
        - file

```

### /tmp/otel.out
```
{
    "resourceLogs": [
        {
            "resource": {},
            "instrumentationLibraryLogs": [
                {
                    "instrumentationLibrary": {},
                    "logs": [
                        {
                            "timeUnixNano": "1640995200000000000",
                            "body": {
                                "stringValue": "\u003cnil\u003e"
                            },
                            "attributes": [
                                {
                                    "key": "timestamp",
                                    "value": {
                                        "stringValue": "0"
                                    }
                                },
                                {
                                    "key": "file.name",
                                    "value": {
                                        "stringValue": "test_timestamp.log"
                                    }
                                }
                            ],
                            "traceId": "",
                            "spanId": ""
                        },
                        {
                            "timeUnixNano": "1640995199000000000",
                            "body": {
                                "stringValue": "\u003cnil\u003e"
                            },
                            "attributes": [
                                {
                                    "key": "timestamp",
                                    "value": {
                                        "stringValue": "31535999"
                                    }
                                },
                                {
                                    "key": "file.name",
                                    "value": {
                                        "stringValue": "test_timestamp.log"
                                    }
                                }
                            ],
                            "traceId": "",
                            "spanId": ""
                        },
                        {
                            "timeUnixNano": "31536000000000000",
                            "body": {
                                "stringValue": "\u003cnil\u003e"
                            },
                            "attributes": [
                                {
                                    "key": "file.name",
                                    "value": {
                                        "stringValue": "test_timestamp.log"
                                    }
                                },
                                {
                                    "key": "timestamp",
                                    "value": {
                                        "stringValue": "31536000"
                                    }
                                }
                            ],
                            "traceId": "",
                            "spanId": ""
                        },
                        {
                            "timeUnixNano": "1609459200000000000",
                            "body": {
                                "stringValue": "\u003cnil\u003e"
                            },
                            "attributes": [
                                {
                                    "key": "file.name",
                                    "value": {
                                        "stringValue": "test_timestamp.log"
                                    }
                                },
                                {
                                    "key": "timestamp",
                                    "value": {
                                        "stringValue": "1609459200"
                                    }
                                }
                            ],
                            "traceId": "",
                            "spanId": ""
                        },
                        {
                            "timeUnixNano": "1640995199000000000",
                            "body": {
                                "stringValue": "\u003cnil\u003e"
                            },
                            "attributes": [
                                {
                                    "key": "file.name",
                                    "value": {
                                        "stringValue": "test_timestamp.log"
                                    }
                                },
                                {
                                    "key": "timestamp",
                                    "value": {
                                        "stringValue": "1640995199"
                                    }
                                }
                            ],
                            "traceId": "",
                            "spanId": ""
                        },
                        {
                            "timeUnixNano": "1640995200000000000",
                            "body": {
                                "stringValue": "\u003cnil\u003e"
                            },
                            "attributes": [
                                {
                                    "key": "file.name",
                                    "value": {
                                        "stringValue": "test_timestamp.log"
                                    }
                                },
                                {
                                    "key": "timestamp",
                                    "value": {
                                        "stringValue": "1640995200"
                                    }
                                }
                            ],
                            "traceId": "",
                            "spanId": ""
                        }
                    ]
                }
            ]
        }
    ]
}
```
