### ISSUE TITLE
Incorrect Documentation to show Process List in a Linux Host

### ISSUE THREAD

**Issue by tjohander-splunk** [signalfx/splunk-otel-collector#1246]
The Smart Agent Receiver config to send Process List data for a linux host is incorrect in [this readme](https://github.com/signalfx/splunk-otel-collector/blob/main/internal/receiver/smartagentreceiver/README.md#configuration)
The required config block needs two elements:
```
receivers:
  smartagent/processlist:
    type: processlist
```
And:
```
service:
  pipelines:
    logs/pslist: <------- This name appears to be significant; it's not an arbitrary name
      receivers:
      - smartagent/processlist
      processors:
      - resourcedetection
      exporters:
      - signalfx
```
This suggested change was validated in the "Splunk Playground" Org running an Ubuntu 20.04 Multipass-based local VM instance.
