### ISSUE TITLE
Add Attribute to Event instead of Field

### ISSUE THREAD

**Issue by PG2000** [signalfx/splunk-otel-collector#1283]
Hello,

my current setup:
A Java Application with a configured Open Telemetry Java Instrumentation Lib sends metadata via resource.attributes 
```json
{
    "resource": {
        "attributes": {
              "x-org-name": "my-org-name"
        }
    }
} 
``` 
Otel Collector:

```yaml
receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:8080"

exporters:
  splunk_hec/traces:
    token: "xxx"
    endpoint: "https://localhost:8000/services/collector"
    source: "otel"
    sourcetype: "otel"
    index: "my-test-index"
    insecure_skip_verify: true
  logging:
    loglevel: debug
    sampling_initial: 5
    sampling_thereafter: 200
```

Currently my custom resource attribute "x-org-name" is send to Splunk in the "Fields" property.
I would like to add the x-org-name resource attribute to the attributes of the Event property for the HEC Exporter

Is there a way to configure this?
