### ISSUE TITLE
splunk_otel_collector_version var is not respected from ansible galaxy deployment

### ISSUE THREAD

**Issue by sloniki** [signalfx/splunk-otel-collector#1457]
When collector is being installed with ansible galaxy collection 0.6.0, var `splunk_otel_collector_version` is not being respected and `latest` version is always being applied.

Example, with this task:
```
tasks:
    - name: "Include splunk_otel_collector"
      include_role:
        name: "signalfx.splunk_otel_collector.collector"
      vars:
        splunk_access_token: YOUR_ACCESS_TOKEN
        splunk_realm: SPLUNK_REALM
        splunk_otel_collector_version: 0.47.0
```

0.48.0 will be installed
