### ISSUE TITLE
Really simple smartagent/statsd and smartagent/appmesh receivers don't seem to be working

### ISSUE THREAD

**Issue by csydvs** [signalfx/splunk-otel-collector#1529]
Hello, we're trying to set up some sort of statsd endpoint to receive traffic from envoy, but have simplified our use case down to the following very simple config:

```
extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  memory_ballast:	
    # In general, the ballast should be set to 1/3 of the collector's memory, the limit	
    # should be 90% of the collector's memory.	
    # The simplest way to specify the ballast size is set the value of SPLUNK_BALLAST_SIZE_MIB env variable.	
    size_mib: ${SPLUNK_BALLAST_SIZE_MIB}	

receivers:
  # This section is used to collect the OpenTelemetry Collector metrics
  # Even if just a Splunk APM customer, these metrics are included
  signalfx:
    endpoint: 0.0.0.0:9943
  smartagent/appmesh:
    type: appmesh
    listenAddress: 0.0.0.0
    listenPort: 8125
  smartagent/statsd:
    type: statsd
    listenAddress: 0.0.0.0
    listenPort: 8126

processors:
  batch:

exporters:
  # Metrics + Events
  signalfx:
    access_token: "${SPLUNK_ACCESS_TOKEN}"
    realm: "${SPLUNK_REALM}"
    api_url: "https://api.${SPLUNK_REALM}.signalfx.com"
    ingest_url: "https://ingest.${SPLUNK_REALM}.signalfx.com"
    correlation:
  logging/info:
    loglevel: "${SPLUNK_LOG_LEVEL}"

service:
  extensions: [health_check]
  telemetry:
    logs:
      level: "${SPLUNK_LOG_LEVEL}"
  pipelines:
    metrics:
      receivers: [signalfx, smartagent/appmesh, smartagent/statsd]
      processors: [batch]
      exporters: [signalfx, logging/info]
```

I'm setting that value into an environment variable (`$SPLUNK_CONFIG_YAML`), and then calling `docker run --rm -e SPLUNK_CONFIG_YAML=$SPLUNK_CONFIG_YAML -e SPLUNK_ACCESS_TOKEN=<my-access-token> -e SPLUNK_REALM='us1' -e SPLUNK_LOG_LEVEL='debug' -e SPLUNK_MEMORY_LIMIT_MIB=450 -e SPLUNK_BALLAST_SIZE_MIB=167 -p 8125:8125 -p 8126:8126 --name otelcol quay.io/signalfx/splunk-otel-collector:0.49.0`. 

The issue is that when I try to run a very simple command `echo "statsd.test:1|g" | nc -w 1 -u 127.0.0.1 8125` or `echo "statsd.test:1|g" | nc -w 1 -u 127.0.0.1 8126`, I don't see anything show up in the logs or in signalfx. Am I missing something obvious in the documentation, or is there a reason that these endpoints wouldn't be accepting my statsd netcat?
