### ISSUE TITLE
Support file inclusion in the config in the same way that community Collector does

### ISSUE THREAD

**Issue by tigrannajaryan** [signalfx/splunk-otel-collector#2536]
The Otel Collector [allows including files](https://opentelemetry.io/docs/collector/configuration/) from the config, e.g.:

```yaml
receivers:
  otlp:
    protocols:
      grpc:

exporters: ${file:receivers.yaml}

service:
  extensions: [ ]
  pipelines:
    traces:
      receivers:  [ otlp ]
      processors: [  ]
      exporters:  [ otlp ]
```

This does not work with Splunk distro of the Collector.

**Comment by rmfitzpatrick** [comment]
This is currently available with the include config source: https://github.com/signalfx/splunk-otel-collector/tree/main/internal/configsource/includeconfigsource

```
config_sources:
  include:

receivers:
  otlp:
    protocols:
      grpc:

exporters: ${include:exporters.yaml}
```

However, we should support this by reconciling the different config managers so that known schemes are forwarded to the registered file provider: https://github.com/signalfx/splunk-otel-collector/blob/f9bb21e8d82303fd42906e9553ca4b45c58d526f/cmd/otelcol/main.go#L97
