### ISSUE TITLE
How to extract timestamp correctly when engine is set as otel

### ISSUE THREAD

**Issue by ndgohel** [signalfx/splunk-otel-collector#2984]
We know how to extract timestamp when engine is fluentd. Timestamps are extracted incorrectly when engine is set as otel

**Comment by atoulme** [comment]
I guess you are using the logEngine otel in the helm chart. Is that correct? If so, please see the following to parse timestamps.
* Identify the `extraOperators` values.yaml configuration key: https://github.com/signalfx/splunk-otel-collector-chart/blob/main/helm-charts/splunk-otel-collector/values.yaml#L536
* https://github.com/open-telemetry/opentelemetry-log-collection/blob/main/docs/operators/json_parser.md
Given your format, I would use:

```
- type: json_parser
  parse_from: body
  timestamp:
    parse_from: body.Timestamp
    layout_type: epoch
    layout: ms
```
