### ISSUE TITLE
how to fetch kubernetes volumes metrics

### ISSUE THREAD

**Issue by xp-1000** [signalfx/splunk-otel-collector#322]
Hello,

I am trying to replace signalfx smart agent by otel collector since its deprecation.

I started with a simple configuration for host, kubernetes and nginx metrics.

```
exporters:
  sapm:
    access_token: ${SPLUNK_ACCESS_TOKEN}
    endpoint: https://ingest.eu0.signalfx.com/v2/trace
  signalfx:
    access_token: ${SPLUNK_ACCESS_TOKEN}
    api_url: https://api.eu0.signalfx.com
    correlation: null
    ingest_url: https://ingest.eu0.signalfx.com
    sync_host_metadata: true
extensions:
  health_check: null
  k8s_observer:
    auth_type: serviceAccount
    node: ${K8S_NODE_NAME}
  zpages: null
processors:
  batch: null
  k8s_tagger:
    extract:
      metadata:
      - namespace
      - node
      - podName
      - podUID
    filter:
      node_from_env_var: K8S_NODE_NAME
  memory_limiter:
    ballast_size_mib: ${SPLUNK_BALLAST_SIZE_MIB}
    check_interval: 5s
    limit_mib: ${SPLUNK_MEMORY_LIMIT_MIB}
  resource:
    attributes:
    - action: insert
      key: host.name
      value: ${K8S_NODE_NAME}
    - action: insert
      key: k8s.node.name
      value: ${K8S_NODE_NAME}
    - action: insert
      key: k8s.cluster.name
      value: kubeoteltest
  resource/add_agent_k8s:
    attributes:
    - action: insert
      key: k8s.pod.name
      value: ${K8S_POD_NAME}
    - action: insert
      key: k8s.pod.uid
      value: ${K8S_POD_UID}
    - action: insert
      key: k8s.namespace.name
      value: ${K8S_NAMESPACE}
  resourcedetection:
    detectors:
    - system
    - env
    override: false
    timeout: 10s
receivers:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu: null
      disk: null
      filesystem: null
      load: null
      memory: null
      network: null
      paging: null
      processes: null
  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14250
      thrift_http:
        endpoint: 0.0.0.0:14268
  kubeletstats:
    auth_type: serviceAccount
    collection_interval: 10s
    endpoint: ${K8S_NODE_IP}:10250
    extra_metadata_labels:
    - container.id
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:55681
  prometheus/agent:
    config:
      scrape_configs:
      - job_name: otel-agent
        scrape_interval: 10s
        static_configs:
        - targets:
          - ${K8S_POD_IP}:8888
          - ${K8S_POD_IP}:24231
  receiver_creator:
    receivers:
      prometheus_simple:
        config:
          endpoint: '`endpoint`:`"prometheus.io/port" in annotations ? annotations["prometheus.io/port"] : 9090`'
          metrics_path: '`"prometheus.io/path" in annotations ? annotations["prometheus.io/path"] : "/metrics"`'
        rule: type == "pod" && annotations["prometheus.io/scrape"] == "true"
      smartagent/nginx:
        config:
          type: collectd/nginx
        rule: type == "port" && pod.name matches "nginx" && port == 80
    watch_observers:
    - k8s_observer
  sapm:
    endpoint: 0.0.0.0:7276
  smartagent/kubernetes_volumes:
    kubeletAPI:
      url: https://${K8S_NODE_IP}:10250
    type: kubernetes-volumes
  smartagent/signalfx-forwarder:
    listenAddress: 0.0.0.0:9080
    type: signalfx-forwarder
  zipkin:
    endpoint: 0.0.0.0:9411
service:
  extensions:
  - health_check
  - k8s_observer
  - zpages
  pipelines:
    metrics:
      exporters:
      - signalfx
      processors:
      - memory_limiter
      - batch
      - resource
      - resourcedetection
      receivers:
      - receiver_creator
      - hostmetrics
      - kubeletstats
      - smartagent/kubernetes_volumes
    metrics/agent:
      exporters:
      - signalfx
      processors:
      - memory_limiter
      - batch
      - resource
      - resource/add_agent_k8s
      - resourcedetection
      receivers:
      - prometheus/agent
    traces:
      exporters:
      - sapm
      - signalfx
      processors:
      - memory_limiter
      - k8s_tagger
      - batch
      - resource
      - resourcedetection
      receivers:
      - otlp
      - jaeger
      - smartagent/signalfx-forwarder
      - zipkin

Events:  <none>
```

It is not clear if native `kubeletstatsreceiver` and `k8sclusterreceiver` from otel collector fully replaces all the `kube*` smart agent monitors (e.g. `kubernetes-events` or `kubernetes-volumes` ..).

For volumes, according to the documentation: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/kubeletstatsreceiver#metric-groups it supports volumes metrics.

I see most of the metrics from `kubernetes-cluster` and `kubelet-metrics` coming to Splunk Observability expect for volume metrics: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/kubeletstatsreceiver/kubelet/volume.go#L27.
However, as you can see in the configuration, `metric_groups` is not defined so it should fetch all metrics including volumes.

Not a big deal given that this receiver is still in beta and the goal of https://github.com/signalfx/splunk-otel-collector/tree/main/internal/receiver/smartagentreceiver is also to be able to keep existing working smart agent monitors waiting for full replacement by opentelemetry collector.
So I tried to configure the original https://docs.signalfx.com/en/latest/integrations/agent/monitors/kubernetes-volumes.html monitor.

Sadly, with the previously shared configuration I got the following error:

```
2021-04-22T17:33:37.356Z    ERROR    volumes/volumes.go:65    Could not get volume metrics    {"kind": "receiver", "name": "smartagent/kubernetes_volumes", "monitorType": "kubernetes-volumes", "error": "failed to get summary stats from Kubelet URL \"https://10.0.2.4:10250/stats/summary/\": kubelet request failed - \"401 Unauthorized\", response: \"Unauthorized\""}
```

So I updated to kubernetes volumes configuration fragment to: 

```
      smartagent/kubernetes_volumes:
        type: kubernetes-volumes
        kubeletAPI:
          authType: serviceAccount
          url: https://${K8S_NODE_IP}:10250
```

But now I get following errors:

```
Error: cannot load configuration: error reading receivers configuration for smartagent/kubernetes_volumes: failed creating Smart Agent Monitor custom config: yaml: unmarshal errors:      
   line 2: field authtype not found in type kubelet.APIConfig                                                                                                                               
 2021/04/22 17:51:23 main.go:74: application run finished with error: cannot load configuration: error reading receivers configuration for smartagent/kubernetes_volumes: failed creating
   line 2: field authtype not found in type kubelet.APIConfig                                                                                                                               
```

According to https://docs.signalfx.com/en/latest/integrations/agent/monitors/kubernetes-volumes.html#configuration `authType` is a valid configuration for `kubeletAPI` nested block so my configuration seems correct.

So maybe it is an "exception" of monitor not compatible with smart agent receiver?

thanks for your help
