### ISSUE TITLE
Unable to set log.file.path as source

### ISSUE THREAD

**Issue by matt14483** [signalfx/splunk-otel-collector#4169]
I am trying to assign the log.file.path attribute as the Splunk source field for the linux files.  However, it seems it is unable to read that attribute.  The fields is getting passed into splunk, and verbose logging is showing it as an attribute, but for some reason, the processor will not pick up that attribute.  Here is an example of my config:
```
processors:
  batch:
    timeout: 2s
  resource:
    attributes:
      - key: host.name
        value: "${HOSTNAME}"
        action: insert
      - key: com.splunk.source
        from_context: log.file.path
        action: insert
```
...
```
receivers:
  fluentforward:
    endpoint: "0.0.0.0:24224"
  filelog:
    include:
      - /Library/Logs/*
      - /var/log/*.log*
      - /var/log/*log
      - /var/log/*messages*
      - /var/log/*secure*
      - /var/log/*auth*
```
...
```
    include_file_name: false
    include_file_path: true


exporters:
  splunk_hec:
```
...
```
service:
  pipelines:
    logs:
      receivers: [fluentforward, filelog]
      processors: [batch, resource]
      exporters: [splunk_hec]
```
