### ISSUE TITLE
Unable to set log.file.path as source (corrected)

### ISSUE THREAD

**Issue by matt14483** [signalfx/splunk-otel-collector#4171]
I am trying to assign the log.file.path attribute as the Splunk source field for the linux files. However, it seems it is unable to read that attribute. The fields is getting passed into splunk, and verbose logging is showing it as an attribute, but for some reason, the processor will not pick up that attribute. Here is an example of my config:
```
processors:
  batch:
    timeout: 2s
  resource:
    attributes:
      - key: host.name
        value: "${HOSTNAME}"
        action: insert
      - key: com.splunk.source
        from_attribute: log.file.path
        action: insert
```
...
```
receivers:
  fluentforward:
    endpoint: "0.0.0.0:24224"
  filelog:
    include:
      - /Library/Logs/*
      - /var/log/*.log*
      - /var/log/*log
      - /var/log/*messages*
      - /var/log/*secure*
      - /var/log/*auth*
```
...
```
    include_file_name: false
    include_file_path: true

exporters:
  splunk_hec:
```
...
```
service:
  pipelines:
    logs:
      receivers: [fluentforward, filelog]
      processors: [batch, resource]
      exporters: [splunk_hec]
```

**Comment by rmfitzpatrick** [comment]
@matt14483 `log.file.path` is a log record attribute and not a [resource](https://opentelemetry.io/docs/specs/otel/resource/sdk/) attribute:

https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/filelogreceiver#configuration
>Whether to add the file path as the attribute log.file.path

I think you would want to use a filelog [operator]](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/docs/operators/README.md#what-operators-are-available) like `move` or `copy`:

```
receivers:
  filelog:
<...>
    operators:
      - from: attributes["log.file.path"]
        to: resource["com.splunk.source"]
        type: move
```

For more assistance please open a support ticket: https://splunk.my.site.com/customer/s/need-help/create-case.
