### ISSUE TITLE
[Question] Otel-collector-contrib --> splunk-otel-collector

### ISSUE THREAD

**Issue by AchimGrolimund** [signalfx/splunk-otel-collector#439]
Hello everybody

I am currently using the "otel-collector-contrib v0.10.0"
I cannot update this to the newer version "0..27.0" because some data are no longer sent to SignalFX.
Furthermore, with our setup today I also have many error messages because we are sending a lot of data.

`otelcontribcol [4539]: 2021/05/31 18:07:00 http: Accept error: accept tcp [::]: 7276: accept4: too many open files; retrying in 160ms`

Now my idea is to switch to "splunk-otel-collector v0.26.0".

Can you recommend this?
Are there any difficulties on the part of collector in this regard?

Our infrastructure looks like this:

onPremise + SignalfxAgent -> otel-collector AWS (autoscaling Ø4-5 Ec2 running)
Openshift4.6 + 59Agents (59Nodes (3500Pods/6000 Container)+500k CustomMetrics ) -> otel-collector AWS
~ 40AWS EC2 + SignalfxAgent -> otelcollector AWS

Here is the config of the OtelCollectors that we are using:
```
extensions:
  health_check:
  zpages:
receivers:
  sapm:
  signalfx:
  # This section is used to collect the OpenTelemetry Collector metrics
  # Even if just a SignalFx µAPM customer, these metrics are included
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: ['localhost:8888']
              # If you want to use the environment filter
              # In the SignalFx dashboard
              labels:
                environment: {{ otel_label_environment }}
          metric_relabel_configs:
            - source_labels: [ __name__ ]
              regex: '.*grpc_io.*'
              action: drop
  # Enable Zipkin to support Istio Mixer Adapter
  # https://github.com/signalfx/signalfx-istio-adapter
  zipkin:
processors:
  batch:
  # Optional: If you have a different environment tag name
  # If this option is enabled it must be added to the pipeline section below
  attributes/copyfromexistingkey:
    actions:
      - key: environment
        from_attribute: env
        action: upsert
  # Optional: If you want to add an environment tag
  # If this option is enabled it must be added to the pipeline section below
  attributes/newenvironment:
    actions:
      - key: environment
        value: "{{ otel_label_environment }}"
        action: insert

  # for demo environment
  attributes/addenvdemo:
    include:
      match_type: regexp
      services: [^test-.*]
    actions:
      - key: environment
        action: upsert
        value: demo

  # for devl environment
  attributes/addenvdevl:
    include:
      match_type: regexp
      services: [.*-devl-.*]
    actions:
      - key: environment
        action: upsert
        value: devl

  # for intg environment
  attributes/addenvintg:
    include:
      match_type: regexp
      services: [.*-intg-.*]
    actions:
      - key: environment
        action: upsert
        value: intg

  # for prod environment
  attributes/addenvprod:
    include:
      match_type: regexp
      services: [.*-prod-.*]
    actions:
      - key: environment
        action: upsert
        value: prod

  # for cicd environment
  attributes/addenvcicd:
    include:
      match_type: regexp
      services: [.*-cicd-.*]
    actions:
      - key: environment
        action: upsert
        value: cicd

  # Add Label to all Ressources
  resource:
    attributes:
    - key: zone
      value: "Company"
      action: upsert
    - key: serviceTime
      value: 1
      action: insert

exporters:
  # Traces
  sapm:
    access_token: "{{exporters_sapm_access_token}}"
    endpoint: "https://ingest.eu0.signalfx.com/v2/trace"
  # Metrics
  signalfx:
    access_token: "{{exporters_signalfx_access_token}}"
    realm: "eu0"
service:
  pipelines:
    traces:
      receivers: [sapm, zipkin]
      processors: [batch, attributes/copyfromexistingkey,attributes/newenvironment,attributes/addenvdemo, attributes/addenvdevl, attributes/addenvintg, attributes/addenvprod, attributes/addenvcicd]
      exporters: [sapm]
    metrics:
      receivers: [signalfx, prometheus]
      processors: [resource, batch]
      exporters: [signalfx]
  extensions: [health_check, zpages]
```

Thank you and have a good start to the day

Greetings Achim
