### ISSUE TITLE
prometheus_simple receiver doesn't stop after a target endpoint dies

### ISSUE THREAD

**Issue by willianvalerio** [signalfx/splunk-otel-collector#471]
The **prometheus_simple** receiver doesn't stop listening to the endpoints after a targeting pod dies
I noticed that when a pod dies, the scrapper keeps trying to scrape metrics from the dead pod. I recorded a video that shows this situation. It looks like a bug

[](url)

https://user-images.githubusercontent.com/7062667/121738683-ec377d80-cad0-11eb-852c-762df0a6285f.mov

I used all default values on the helm chart following the wizard.

The prometheus_simple receiver comes as a default within the **receiver_creator**

```yaml
receivers:
  receiver_creator:
    receivers:
      prometheus_simple:
        config:
          endpoint: '`endpoint`:`"prometheus.io/port" in annotations ? annotations["prometheus.io/port"]
            : 9090`'
          metrics_path: '`"prometheus.io/path" in annotations ? annotations["prometheus.io/path"]
            : "/metrics"`'
        rule: type == "pod" && annotations["prometheus.io/scrape"] == "true"
```

Istio version (prometheus endpoints): 1.10.0
Helm chart: 0.26.4
Kubernetes(k3s): 1.21.1
S.O.: Ubuntu 20.04
