### ISSUE TITLE
Otel collector with vaultconfigsource

### ISSUE THREAD

**Issue by aishvaryaps** [signalfx/splunk-otel-collector#486]
I am following : splunk-otel-collector/internal/configsource/vaultconfigsource/

I need to hide the database password using Vault by HashiCorp. I have installed vault by HashiCorp on a machine and able to retrieved secrets with :
**_vault kv get secret/token_**

Now I have configured vault in agent_config.yaml as below:

 **_config_sources:
  vault:
    endpoint: http://127.0.0.1:8200
    path: secret/data/token
    poll_interval: 90s
    auth:
      token: s.fT85.................................._**

Now for mysql collectd plugin my configuration to read password from vault is as below:
  **_smartagent/sql:
    type: collectd/mysql
    host: 127.0.0.1
    port: 3306
    databases:
      - name: demo
    username: root
    password: $vault:data.mysql_**

I see below error in agent.yaml:
![image](https://user-images.githubusercontent.com/48279639/122355060-35734b80-cf6f-11eb-8b7b-97d65b7975f7.png)

Please let me now where I am going wrong

**Comment by jrcamp** [comment]
@pjanotti

**Comment by aishvaryaps** [comment]
Hi @jrcamp @pjanotti Can you please provide some update? Thanks :)

**Comment by pjanotti** [comment]
Sorry @aishvaryaps for the long delay to get to this issue.

I tried to repro but no luck. I used a trimmed down config file to quickly test the collector:
```yaml
config_sources:
  vault:
    endpoint: http://127.0.0.1:8200
    path: secret/data/token
    poll_interval: 10s
    auth:
      token: s.tk...

receivers:
  zipkin:
exporters:
  file:
    path: $vault:data.mysql

service:
  pipelines:
    traces:
      receivers: [zipkin]
      exporters: [file]
```

and setup kv store with the following commands:
```terminal
vault kv put secret/token mysql=filename_change
vault kv get secret/token
```

I tried both with a local vault dev server and a docker container. At this point, the 2 top candidates for this are some differences while setting up the vault secret or some typo on the vault token specified in the config file. 

How did you setup the vault secret?
