### ISSUE TITLE
memory_limiter cannot be configured in the config yaml

### ISSUE THREAD

**Issue by dmitryax** [signalfx/splunk-otel-collector#541]
The `otelcol` binary expects that `memory_limiter` can be configured only with env vars. If it's configured solely in config yaml, for example:
```
      memory_limiter:
        ballast_size_mib: "4096"
        check_interval: 1s
        limit_mib: "8192"
        spike_limit_mib: "2560"
```
the collector is failing to start with the following message
```
main.go:283: Memory limit (460) is less than 2x ballast (4096). Increase memory limit or decrease ballast size.
```

If `--mem-ballast-size-mib` is not provided, the collector will start but misconfigured:
```
memory_limiter is likely incorrectly configured. ballast_size_mib must be set equal to --mem-ballast-size-mib command line option.	{"kind": "processor", "name": "memory_limiter"}
```
