### ISSUE TITLE
get Hostmetrics from gateway

### ISSUE THREAD

**Issue by AchimGrolimund** [signalfx/splunk-otel-collector#618]
Hi, everyone

I have a Kubernetes running with ~ 6k pods.

that's why I created a gateway on AWS. now I would like to see the host metrics such as DiskUtilazation CPU.Utilization etc from the gateway.

What should I do best about it?

Can the splunk-otel-collector also read out the host metrics as a receiver in gateway mode or do I have to start the splunk-otel-collector twice? as an agent and as a gateway?

Best regards

PS: atm i use the Default config given from signalfx datasetup.

**Comment by dmitryax** [comment]
Hi @AchimGrolimund, yes, it's possible to collect metrics from the gateway.

You just need to define an additional `hostmetrics` receiver as done in [the agent config](https://github.com/signalfx/splunk-otel-collector/blob/main/cmd/otelcol/config/collector/agent_config.yaml#L39-L54) and add it to the list of receivers in [the default metrics pipeline](https://github.com/signalfx/splunk-otel-collector/blob/main/cmd/otelcol/config/collector/gateway_config.yaml#L110).

Couple of questions:
- Is the gateway deployed on an EC2 instance outside of k8s cluster?
- Do you send metrics and traces there using otlp format?

**Comment by AchimGrolimund** [comment]
Hello @dmitryax 

yes the gateway is not within the k8s cluster. It's in a different AWS account.

At the moment I'm still testing it, but later traces events and metrics will also run on it.

I'm not exactly sure about the format. currently I still use the SignalFX agents and an opentelemetrie-collector-contrib as a gateway. as far as I can tell, the signalFx agents send in SAPM format. All of this should then be replaced by the Splunk-Otel-collector.

**Comment by AchimGrolimund** [comment]
Hey @dmitryax 

thank you again for your help and explanation.
I have now inserted this like this. however, I find the values that arrive very strange.
I can't find a connection with any scraper that I see on my EC2
Example memory, shows me 2 and 3, but the consumption is around 50%

can it be that I still have to define the individual "monitors" more? At the moment I was doing it like in agent mode

```yaml
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      disk:
      filesystem:
      memory:
      network:
      load:
      paging:
      processes:
```
that's how I inserted it

and then added this receiver to the standard metrics pipeline as described.

```yaml
    metrics:
      receivers: [hostmetrics, otlp, signalfx]
      processors: [memory_limiter, batch]
      exporters: [signalfx]

```

![image](https://user-images.githubusercontent.com/22026079/129148126-3adf357d-7017-4b15-9f99-fc539c9d362b.png)

**Comment by dmitryax** [comment]
Hi @AchimGrolimund, 

> Example memory, shows me 2 and 3, but the consumption is around 50%

Sorry, I don't fully understand the problem. To clarify, the chart that you posted shows `otelcol_scraper_scraped_metric_points` metric which represents amount of metric points scraped from the system by the collector, not the system metric values themselves. The scraped system metrics can be found in the Hosts dashboard in o11y UI. Do you see the new host running the gateway in your Hosts dashboard?

> can it be that I still have to define the individual "monitors" more? At the moment I was doing it like in agent mode

The configuration that you added looks good to me. Did you make any other changes to the default gateway config?

**Comment by AchimGrolimund** [comment]
Hey @dmitryax 

No i do dont change anything.
i have used the installer script to install the splunk-otel-collector and add the Metrics Reciver.

Here the full config file:
```yaml
cat /etc/otel/collector/gateway_config.yaml
# Configuration file that uses the Splunk exporters (SAPM, SignalFx) to push
# data to Splunk products.

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  http_forwarder:
    ingress:
      endpoint: 0.0.0.0:6060
    egress:
      endpoint: "https://api.${SPLUNK_REALM}.signalfx.com"
  zpages:
    endpoint: 0.0.0.0:55679
  memory_ballast:
    # In general, the ballast should be set to 1/3 of the collector's memory, the limit
    # should be 90% of the collector's memory.
    # The simplest way to specify the ballast size is set the value of SPLUNK_BALLAST_SIZE_MIB env variable.
    size_mib: ${SPLUNK_BALLAST_SIZE_MIB}

receivers:
  ## --> This Metrics i can not find in SignalFX
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      disk:
      filesystem:
      memory:
      network:
      load:
      paging:
      processes:
  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14250
      thrift_binary:
        endpoint: 0.0.0.0:6832
      thrift_compact:
        endpoint: 0.0.0.0:6831
      thrift_http:
        endpoint: 0.0.0.0:14268
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:55681
  # This section is used to collect the OpenTelemetry Collector metrics
  # Even if just a Splunk APM customer, these metrics are included
  prometheus/internal:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 10s
        static_configs:
        - targets: ['0.0.0.0:8888']
        metric_relabel_configs:
          - source_labels: [ __name__ ]
            regex: '.*grpc_io.*'
            action: drop
  sapm:
    endpoint: 0.0.0.0:7276
  signalfx:
    endpoint: 0.0.0.0:9943
  zipkin:
    endpoint: 0.0.0.0:9411

processors:
  batch:
  # Enabling the memory_limiter is strongly recommended for every pipeline.
  # Configuration is based on the amount of memory allocated to the collector.
  # For more information about memory limiter, see
  # https://github.com/open-telemetry/opentelemetry-collector/blob/main/processor/memorylimiter/README.md
  memory_limiter:
    check_interval: 2s
    limit_mib: ${SPLUNK_MEMORY_LIMIT_MIB}

  # Optional: The following processor can be used to add a default "deployment.environment" attribute to the traces
  # when it's not populated by instrumentation libraries.
  # If enabled, make sure to enable this processor in the pipeline below.
  #resource/add_environment:
    #attributes:
      #- action: insert
        #value: staging/production/...
        #key: deployment.environment

  # detect if the collector is running on a cloud system.
  # overrides resource attributes set by receivers
  resourcedetection/internal:
    detectors: [system, gce, ecs, ec2, azure]
    override: true

exporters:
  # Traces
  sapm:
    access_token: "${SPLUNK_ACCESS_TOKEN}"
    endpoint: "https://ingest.${SPLUNK_REALM}.signalfx.com/v2/trace"
  # Metrics + Events
  signalfx:
    access_token: "${SPLUNK_ACCESS_TOKEN}"
    realm: "${SPLUNK_REALM}"
    ## Uncomment below if your agents are sending via signalfx exporter
    ## to avoid double translations and exclusions.
    #translation_rules: []
    #exclude_metrics: []
  # Debug
  #logging:
    #loglevel: debug

service:
  extensions: [health_check, http_forwarder, zpages, memory_ballast]
  pipelines:
    traces:
      receivers: [jaeger, otlp, sapm, zipkin]
      processors:
      - memory_limiter
      - batch
      #- resource/add_environment
      exporters: [sapm, signalfx]
    metrics:
      receivers: [hostmetrics, otlp, signalfx]
      processors: [memory_limiter, batch]
      exporters: [signalfx]
    metrics/internal:
      receivers: [prometheus/internal]
      processors: [memory_limiter, batch, resourcedetection/internal]
      exporters: [signalfx]
    logs:
      receivers: [signalfx]
      processors: [memory_limiter, batch]
      exporters: [signalfx]
```

**Comment by AchimGrolimund** [comment]
hey @dmitryax 
I have good news

I may have found a bug.

I've watched the documentaries here and all the examples. I noticed that only these recivers were given in one example:
```yaml
receivers:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      disk:
      filesystem:
      memory:
      network:
```
then I have now removed the others:

```yaml
      load:
      paging:
      processes:
```

What I also saw in the examples that the `resourcedetection` was added to the pipeline. I did this too and I am now receiving data

```yaml
service:
  extensions: [health_check, http_forwarder, zpages, memory_ballast]
  pipelines:
    metrics:
      receivers: [hostmetrics, otlp, signalfx]
      processors: [memory_limiter, batch, resourcedetection/internal]
      exporters: [signalfx]
```

![image](https://user-images.githubusercontent.com/22026079/129349044-71129b68-e11c-40ac-8eaa-29c830010be2.png)
