### ISSUE TITLE
Agent errors and OOM when encountering NaN metrics

### ISSUE THREAD

**Issue by gingerwizard** [signalfx/splunk-otel-collector#796]
**Describe the bug**
Splunk Hec Exporter fails on NaN values and eventually OOM.

**Steps to reproduce**

1. Deploy open telemetry collector with the splunk hec exporter
2. Use a Prometheus receiver to monitor kube state metrics

**What did you expect to see?**

Either support NaN values through filtering.

**What did you see instead?**

> 2021-10-04T12:59:52.255Z	error	exporterhelper/queued_retry.go:288	Exporting failed. The error is not retryable. Dropping data.	{"kind": "exporter", "name": "splunk_hec/platformMetrics", "error": "Permanent error: json: unsupported value: NaN", "dropped_items": 121834}
> go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
> 	/builds/o11y-gdi/splunk-otel-collector-releaser/.go/pkg/mod/go.opentelemetry.io/collector@v0.33.0/exporter/exporterhelper/queued_retry.go:288
> go.opentelemetry.io/collector/exporter/exporterhelper.(*metricsSenderWithObservability).send
> 	/builds/o11y-gdi/splunk-otel-collector-releaser/.go/pkg/mod/go.opentelemetry.io/collector@v0.33.0/exporter/exporterhelper/metrics.go:117
> go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1
> 	/builds/o11y-gdi/splunk-otel-collector-releaser/.go/pkg/mod/go.opentelemetry.io/collector@v0.33.0/exporter/exporterhelper/queued_retry.go:155
> github.com/jaegertracing/jaeger/pkg/queue.ConsumerFunc.Consume
> 	/builds/o11y-gdi/splunk-otel-collector-releaser/.go/pkg/mod/github.com/jaegertracing/jaeger@v1.25.0/pkg/queue/bounded_queue.go:104
> github.com/jaegertracing/jaeger/pkg/queue.(*BoundedQueue).StartConsumersWithFactory.func1
> 	/builds/o11y-gdi/splunk-otel-collector-releaser/.go/pkg/mod/github.com/jaegertracing/jaeger@v1.25.0/pkg/queue/bounded_queue.go:83
> 

**What version did you use?**

    Image:         quay.io/signalfx/splunk-otel-collector:0.33.1

**What config did you use?**

```
exporters:
  splunk_hec/platformMetrics:
    disable_compression: true
    endpoint: http://splunk-8-service:8088/services/collector
    index: em_metrics
    insecure: 
    insecure_skip_verify: false
    max_connections: 200
    source: kubernetes
    sourcetype: null
    timeout: 10s
    token: ${SPLUNK_PLATFORM_HEC_TOKEN}
extensions:
  health_check: null
processors:
  batch: null
  memory_limiter:
    ballast_size_mib: ${SPLUNK_BALLAST_SIZE_MIB}
    check_interval: 5s
    limit_mib: ${SPLUNK_MEMORY_LIMIT_MIB}
  resource:
    attributes:
    - action: insert
      key: metric_source
      value: kubernetes
    - action: insert
      key: receiver
      value: k8scluster
    - action: upsert
      key: k8s.cluster.name
      value: dev-us-central-0
  resource/add_collector_k8s:
    attributes:
    - action: insert
      key: k8s.node.name
      value: ${K8S_NODE_NAME}
    - action: insert
      key: k8s.pod.name
      value: ${K8S_POD_NAME}
    - action: insert
      key: k8s.pod.uid
      value: ${K8S_POD_UID}
    - action: insert
      key: k8s.namespace.name
      value: ${K8S_NAMESPACE}
  resourcedetection:
    detectors:
    - system
    - env
    - gke
    - gce
    override: false
    timeout: 10s
receivers:
  k8s_cluster:
    auth_type: serviceAccount
  prometheus:
    config:
      scrape_configs:
      - job_name: kube-state-metrics
        metrics_path: /metrics
        scrape_interval: 30s
        static_configs:
        - targets:
          - kube-state-metrics.default.svc.cluster.local:8080
  prometheus/k8s_cluster_receiver:
    config:
      scrape_configs:
      - job_name: otel-k8s-cluster-receiver
        scrape_interval: 10s
        static_configs:
        - targets:
          - ${K8S_POD_IP}:8889
service:
  extensions:
  - health_check
  pipelines:
    metrics:
      exporters:
      - splunk_hec/platformMetrics
      processors:
      - memory_limiter
      - batch
      - resource
      receivers:
      - prometheus
      - k8s_cluster
    metrics/collector:
      exporters:
      - splunk_hec/platformMetrics
      processors:
      - memory_limiter
      - batch
      - resource
      - resource/add_collector_k8s
      - resourcedetection
      receivers:
      - prometheus/k8s_cluster_receiver


```
